routes/web.php
<?php

use App\Http\Controllers\JuiceController;
use App\Models\ProductJuice;
use Illuminate\Support\Facades\Route;   

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::resource('/juices', JuiceController::class);  

resources/views/juiceManagement/app.blade.php
@extends('manageLayouts.app')

@section('content')
    <div class="container" style="background-color:white">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>Saltnic's World</h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-success" href="{{ route('juices.create') }}" title="Create a juice">Create a juice <i class="fas fa-plus-circle"></i>
                        </a>
                </div>
            </div>
        </div>
    
        @if ($message = Session::get('success'))
            <div class="alert alert-success">   
                <p>{{ $message }}</p>
            </div>
        @endif
    
        <table class="table table-bordered table-responsive-lg" style="margin-top: 10px">
            <tr>
              <td>ID</td>
              <td>Product name</td>
              <td>Number</td>
              <td>Image</td>
              <td>Nicotin</td>
              <td>Flavor</td>
              <td>Brand</td>
              <td>Price</td>
              <td>Sell Price</td>
                <th width="120px">Action</th>
            </tr>
            @foreach ($juices as $juice)
                <tr>
                    <td>{{ ++$i }}</td>
                    <td>{{ $juice->juicename }}</td>
                    <td>{{ $juice->number }}</td>
                    <td><img src="{{ $juice->image }}" alt="" style="width:100px;height:100px;"></td>
                    <td>{{ $juice->nicotin }}</td>
                    <td>{{ $juice->flavor }}</td>
                    <td>{{ $juice->brand }}</td>
                    <td>{{ $juice->price }}</td>
                    <td>{{ $juice->sellingprice}}</td>
                    <td>
                        <form action="{{ route('juices.destroy', $juice->id) }}" method="POST">
    
                            <a href="{{ route('juices.show', $juice->id) }}" title="show">
                                <i class="fas fa-eye text-success  fa-lg"></i>
                            </a>
    
                            <a href="{{ route('juices.edit', $juice->id) }}">
                                <i class="fas fa-edit  fa-lg"></i>
    
                            </a>
    
                            @csrf
                            @method('DELETE')
    
                            <button type="submit" title="delete" style="border: none; background-color:transparent;">
                                <i class="fas fa-trash fa-lg text-danger"></i>
    
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>          
    </div>
    {!! $juices->links() !!}  

@endsection

resources/views/juiceManagement/create.blade.php
@extends('manageLayouts.app')

@section('content')
    <div class="container" style="background-color: white">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>Add New Product</h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{ route('juices.index') }}" title="Go back">Return <i class="fas fa-backward "></i> </a>
                </div>
            </div>
        </div>
    
        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form action="{{ route('juices.store') }}" method="POST" >
            @csrf
    
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Product Name:</strong>
                        <input type="text" name="juicename" class="form-control" placeholder="Name">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Number:</strong>
                        <input type="number" class="form-control" style="height:50px" name="number"
                            placeholder="Number"></textarea>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Image:</strong>
                        <input type="file" name="image" class="form-control" placeholder="">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Nicotin:</strong>
                        <input type="number" name="nicotin" class="form-control" placeholder="Nicotin">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Flavor:</strong>
                        <input type="text" name="flavor" class="form-control" placeholder="Flavor">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Brand:</strong>
                        <input type="text" name="brand" class="form-control" placeholder="Brand">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Price:</strong>
                        <input type="number" min="1" step="any" name="price" class="form-control" placeholder="Price">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Selling Price:</strong>
                        <input type="number" min="1" step="any" name="sellingprice" class="form-control" placeholder="Selling-Price">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
    
        </form>
    </div>
@endsection

resources/views/juiceManagement/edit.blade.php
@extends('manageLayouts.app')

@section('content')
    <div class="container" style="background-color: white">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>Update Product{{ $juice->juicename }}</h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{ route('juices.index') }}" title="Go back">Return <i class="fas fa-backward "></i> </a>
                </div>
            </div>
        </div>
    
        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form action="{{ route('juices.update', $juice->id) }}" method="POST" >
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Product Name:</strong>
                        <input type="text" name="juicename" class="form-control" value="{{ $juice->juicename }}" placeholder="Name">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Number:</strong>
                        <input type="number" class="form-control" style="height:50px" name="number"
                            value="{{ $juice->number }}" placeholder="Number"></textarea>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Image:</strong>
                        <img src="{{ $juice->image }}" alt="" style="width:100px;height:100px">
                        <input type="file" name="image" class="form-control"  placeholder="">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Nicotin:</strong>
                        <input type="number" name="nicotin" class="form-control" value="{{ $juice->nicotin }}" placeholder="Nicotin">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Flavor:</strong>
                        <input type="text" name="flavor" class="form-control" value="{{ $juice->flavor }}" placeholder="Flavor">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Brand:</strong>
                        <input type="text" name="brand" class="form-control" value="{{ $juice->brand }}" placeholder="Brand">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Price:</strong>
                        <input type="number" min="1" step="any" name="price" class="form-control" value="{{ $juice->price }}" placeholder="Price">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Selling Price:</strong>
                        <input type="number" min="1" step="any" name="sellingprice" class="form-control" value="{{ $juice->sellingprice }}" placeholder="Selling-Price">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </div>
    
        </form>
    </div>
@endsection

resources/views/juiceManagement/show.blade.php
@extends('manageLayouts.app')


@section('content')
    <div class="container" style="background-color: white">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>  Sản phẩm {{ $juice->juicename }}</h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{ route('juices.index') }}" title="Go back">Go back <i class="fas fa-backward "></i> </a>
                </div>
            </div>
        </div>
    
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Product Name: {{ $juice->juicename }}</strong></div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Number: {{ $juice->number }}</strong>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Image: </strong><img src="{{ $juice->image }}" alt="" style="width:100px;height:100px;"></div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Nicotin: {{ $juice->nicotin }}</strong></div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Flavor: {{ $juice->flavor }}</strong></div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Brand: {{ $juice->brand }}</strong></div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Price: {{ $juice->price }}</strong></div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Selling Price: {{ $juice->sellingprice }}</strong></div>
            </div>
        </div>
    </div>
@endsection